version: '3.7'
services:
    dbAsteSnap:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - 5432:5432
        volumes: 
          - ./scripts/full.sql:/docker-entrypoint-initdb.d/full.sql          
    web-node:
        build: .
        restart: always
        ports:
          - 8080:8080
        environment:
          - PGUSER=postgres
          - PGDATABASE=aste_snap
          - PGHOST=dbAsteSnap
          - PGPASSWORD=postgres
          - PGPORT=5432
        env_file:
          - .env  
        depends_on:
          - dbAsteSnap
